version: "2.3"

services:
  osrm-backend:
    image: monogramm/docker-osrm-backend:${OSRM_VERSION}
    container_name: osrm-backend
    ports:
      - "5000:5000"
    volumes:
      - ${OSRM_BACKEND_HOME}/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - OSRM_ALGORITHM=mld
      - OSRM_THREADS=2
      - OSRM_PORT=5000
      - OSRM_PROFILE=/opt/car.lua
      - OSRM_MAP_NAME=${OSRM_MAP_NAME}
      - OSRM_GEOFABRIK_PATH=${OSRM_GEOFABRIK_PATH}
      - OSRM_NOTIFY_FILEPATH=/data/osrm_notify.txt

  osrm-frontend:
    image: osrm/osrm-frontend:latest
    container_name: osrm-frontend
    ports:
      - "8080:9966"
    depends_on:
      osrm-backend:
        condition: service_started
    environment:
      - OSRM_BACKEND=http://osrm-backend:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "3000:3000"
    depends_on:
      osrm-backend:
        condition: service_started
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=3000